name: Build with Pyinstaller

on:
  release:
    types: [published]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ./

      # Build with PyInstaller
      - name: Build windows executable
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller scripts.py `
            --noconfirm `
            --noconsole `
            --clean `
            --name "shg_frog" `
            --add-data "src/shg_frog/data;data" `

      - name: Build linux/mac executable
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          pyinstaller scripts.py \
            --noconfirm \
            --noconsole \
            --clean \
            --name "shg_frog" \
            --add-data "src/shg_frog/data:data" \

      # Archive the build output
      - name: Create archive (linux/mac)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          cd dist
          zip -r ../shg_frog-${{ github.event.release.tag_name }}-${{ matrix.os }}.zip shg_frog/

      - name: Create archive (windows)
        if: matrix.os == 'windows-latest'
        run: |
          Compress-Archive -Path dist\shg_frog\* -DestinationPath shg_frog-${{ github.event.release.tag_name }}-${{ matrix.os }}.zip

      # Upload the archive as a release asset
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: shg_frog-${{ github.event.release.tag_name }}-${{ matrix.os }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
